---
- name: 'Common configuration and programs'
  hosts: 'all'
  become: yes
  roles:
    - 'ubuntu-setup'
    - 'docker-setup'
    - 'docker-socket-proxy'
    - 'traefik'

- name: 'Setup Nextcloud'
  hosts: 'nextcloud'
  become: yes
  roles:
    - 'nextcloud'

#- name: 'Setup Mattermost'
#  hosts: 'mattermost'
#  become: yes
#  roles:
#    - 'mattermost'

- name: 'Setup Rocket.Chat'
  hosts: 'rocketchat'
  become: yes
  roles:
    - 'rocket-chat'

- name: 'Setup Moodle'
  hosts: 'moodle'
  become: yes
  roles:
    - 'moodle'

- name: 'Setup DokuWiki'
  hosts: 'dokuwiki'
  become: yes
  roles:
    - 'dokuwiki'
