---
- name: 'Setup the host'
  hosts: 'services-host'
  become: yes
  roles:
    - 'ubuntu-setup'
    - 'docker-setup'

- name: 'Setup the services'
  hosts: 'services-host'
  become: yes
  roles:
    - 'docker-socket-proxy'
    - 'traefik'
    - 'nextcloud'
#    - 'mattermost'
    - 'rocket-chat'
