---
- name: 'Services'
  hosts: 'all'
  become: yes
  vars_files:
    - 'vaults/{{ target_environment }}.yml'
  roles:
    - 'ufw_setup'
    - 'docker_install'
    - 'docker_socket_proxy'
    - 'traefik'
    - role: 'nextcloud'
      when: '"nextcloud" in group_names'
    - role: 'mattermost'
      when: '"mattermost" in group_names'
    #- role: 'rocketchat'
    #  when: '"rocketchat" in group_names'
    - role: 'moodle'
      when: '"moodle" in group_names'
    - role: 'dokuwiki'
      when: '"dokuwiki" in group_names'
