---
mattermost_image_tag: 'latest'
mattermost_postgres_image_tag: 'latest'
mattermost_postgres_database: 'mattermost'
mattermost_postgres_user: 'mattermost'
mattermost_postgres_password: 'mattermost'
