---
- name: 'Upgrade all packages'
  ansible.builtin.apt:
    name: '*'
    state: 'latest'
    update_cache: yes

- name: 'Install useful packages'
  ansible.builtin.apt:
    name:
      - 'rsync'
      - 'htop'
      - 'curl'
      - 'vim'
      - 'git'
      - 'ufw'
      - 'python3'
    state: 'present'

- name: 'Allow SSH in firewall'
  community.general.ufw:
    rule: 'allow'
    name: 'OpenSSH'

- name: 'Enable the firewall'
  community.general.ufw:
    state: 'enabled'
