---
- name: 'Upgrade all packages'
  ansible.builtin.apt:
    name: '*'
    state: 'latest'
    update_cache: yes

- name: 'Install useful packages'
  ansible.builtin.apt:
    name:
      - 'rsync'
      - 'htop'
      - 'curl'
      - 'vim'
      - 'git'
      - 'ufw'
      - 'python3'
    state: 'present'

- name: 'Configure default access rules in firewall'
  community.general.ufw:
    default: '{{ item.default }}'
    direction: '{{ item.direction }}'
  loop:
    - default: 'deny'
      direction: 'incoming'
    - default: 'allow'
      direction: 'outgoing'

- name: 'Allow SSH in firewall'
  community.general.ufw:
    rule: 'allow'
    port: 'ssh'
    proto: 'tcp'

- name: 'Enable the firewall'
  community.general.ufw:
    state: 'enabled'
