---
- name: 'Upgrade all packages'
  ansible.builtin.apt:
    name: '*'
    state: 'latest'
    update_cache: yes

- name: 'Install useful packages'
  ansible.builtin.apt:
    name:
      - 'rsync'
      - 'htop'
      - 'curl'
      - 'vim'
      - 'git'
    state: 'present'

- name: 'Install required docker-ce dependencies'
  ansible.builtin.apt:
    name:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'gnupg-agent'
      - 'software-properties-common'
    state: 'present'

- name: 'Import docker-ce repository PGP key into apt'
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: 'present'

- name: 'Add docker-ce repository'
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distribution_release }} stable'
    state: 'present'

- name: 'Install docker-ce'
  ansible.builtin.apt:
    name:
      - 'docker-ce'
      - 'docker-ce-cli'
      - 'containerd.io'

- name: 'Enable and start docker'
  ansible.builtin.systemd:
    name: 'docker.service'
    state: 'started'
    enabled: yes
