---
timezone: 'Europe/Paris'
containers_config_path: '/opt/containers/config'
containers_data_path: '/opt/containers/data'
traefik_image_tag: '2.4'
nextcloud_image_tag: '20'
nextcloud_mariadb_image_tag: '10'
nextcloud_redis_image_tag: '6'
mattermost_image_tag: '5'
mattermost_postgres_image_tag: '13'
rocketchat_image_tag: '3.9'
rocketchat_mongo_image_tag: '4.0'
moodle_image_tag: '3'
moodle_mariadb_image_tag: '10'
