---
timezone: 'Europe/Paris'
containers_config_path: '/opt/containers/config'
containers_data_path: '/opt/containers/data'
traefik_image_tag: '2.4'
nextcloud_image_tag: '20'
nextcloud_mariadb_image_tag: '10'
nextcloud_redis_image_tag: '6'
