---
- name: 'Create Moodle data directory'
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'directory'
  loop:
    - '{{ containers_data_path }}/moodle'

- name: 'Create MariaDB data directory'
  ansible.builtin.file:
    path: '{{ containers_data_path }}/moodle_mariadb/db'
    state: 'directory'

- name: 'Create docker networks'
  community.general.docker_network:
    name: '{{ item.name }}'
    internal: '{{ item.internal }}'
    state: 'present'
  loop:
    - name: 'web-proxy'
      internal: no
    - name: 'internal'
      internal: yes

- name: 'Create the MariaDB container'
  community.general.docker_container:
    name: 'moodle_mariadb'
    image: 'mariadb:{{ moodle_mariadb_image_tag }}'
    restart_policy: 'unless-stopped'
    networks:
      - name: 'internal'
        aliases: 'moodle_mariadb'
    network_mode: 'internal'
    volumes:
      - '{{ containers_data_path }}/moodle_mariadb/db:/var/lib/mysql'
    env:
      TZ: '{{ timezone }}'
      MYSQL_ROOT_PASSWORD: '{{ moodle.mariadb.root_password }}'
      MYSQL_USER: '{{ moodle.mariadb.user }}'
      MYSQL_PASSWORD: '{{ moodle.mariadb.password }}'
      MYSQL_DATABASE: '{{ moodle.mariadb.database }}'
    container_default_behavior: 'no_defaults'
    networks_cli_compatible: yes
    purge_networks: yes
    pull: yes
    state: 'started'

- name: 'Create the Moodle container'
  community.general.docker_container:
    name: 'moodle'
    image: 'bitnami/moodle:{{ moodle_image_tag }}'
    restart_policy: 'unless-stopped'
    networks:
      - name: 'web-proxy'
        aliases: 'moodle'
      - name: 'internal'
        aliases: 'moodle'
    network_mode: 'web-proxy'
    volumes:
      - '{{ containers_data_path }}/moodle:/bitnami/moodle'
    env:
      TZ: '{{ timezone }}'
      MOODLE_USERNAME: '{{ moodle.user }}'
      MOODLE_PASSWORD: '{{ moodle.password }}'
      MOODLE_DATABASE_TYPE: 'mariadb'
      MOODLE_DATABASE_HOST: 'moodle_mariadb'
      MOODLE_DATABASE_NAME: '{{ moodle.mariadb.database }}'
      MOODLE_DATABASE_USER: '{{ moodle.mariadb.user }}'
      MOODLE_DATABASE_PASSWORD: '{{ moodle.mariadb.password }}'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.learn.rule: 'Host(`learn.{{ domain_name }}`)'
      traefik.http.routers.learn.entrypoints: 'websecure'
      traefik.http.routers.learn.middlewares: 'set-security-headers@file'
      traefik.http.services.learn.loadbalancer.server.port: '8080'
    container_default_behavior: 'no_defaults'
    networks_cli_compatible: yes
    purge_networks: yes
    pull: yes
    state: 'started'
