all:
  children:
    nextcloud:
      hosts:
        nextcloud-host:
          ansible_host: '10.1.6.11'
    mattermost:
      hosts:
        mattermost-host:
          ansible_host: '10.1.6.14'
    rocketchat:
      hosts:
        rocketchat-host:
          ansible_host: '10.1.6.14'
    moodle:
      hosts:
        moodle-host:
          ansible_host: '10.1.6.12'
    dokuwiki:
      hosts:
        dokuwiki-host:
          ansible_host: '10.1.6.13'
  vars:
    target_environment: 'production'
    traefik_image_tag: '2.4'
    nextcloud_image_tag: '20'
    nextcloud_mariadb_image_tag: '10'
    nextcloud_redis_image_tag: '6'
    mattermost_image_tag: '5'
    mattermost_postgres_image_tag: '13'
    rocketchat_image_tag: '3.9'
    rocketchat_mongo_image_tag: '4.0'
    moodle_image_tag: '3'
    moodle_mariadb_image_tag: '10'
    dokuwiki_image_tag: '20200729'
