---
- name: 'Create config and data directories'
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  loop:
    - '{{ containers_config_path }}/traefik/config'
    - '{{ containers_data_path }}/traefik/data'

- name: 'Create acme.json file'
  ansible.builtin.file:
    path: '{{ containers_data_path }}/traefik/data/acme.json'
    state: 'touch'
    access_time: 'preserve'
    modification_time: 'preserve'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: 'Create trafik config files from template'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
  loop:
    - src: 'traefik.toml.j2'
      dest: '{{ containers_config_path }}/traefik/config/traefik.toml'
    - src: 'traefik-dynamic.toml.j2'
      dest: '{{ containers_config_path }}/traefik/config/traefik-dynamic.toml'

- name: 'Authorize HTTP and HTTPS in firewall'
  community.general.ufw:
    rule: 'allow'
    port: '{{ item }}'
    proto: 'tcp'
  loop:
    - '80'
    - '443'

- name: 'Create docker networks'
  community.general.docker_network:
    name: '{{ item.name }}'
    internal: '{{ item.internal }}'
    state: 'present'
  loop:
    - name: 'web-proxy'
      internal: no
    - name: 'socket-proxy'
      internal: yes

- name: 'Create the Traefik container'
  community.general.docker_container:
    name: 'traefik'
    image: 'traefik:{{ traefik_image_tag }}'
    restart_policy: 'unless-stopped'
    networks:
      - name: 'web-proxy'
        aliases: 'traefik'
      - name: 'socket-proxy'
        aliases: 'traefik'
    network_mode: 'web-proxy'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '{{ containers_config_path }}/traefik/config/traefik.toml:/etc/traefik/traefik.toml'
      - '{{ containers_config_path }}/traefik/config/traefik-dynamic.toml:/etc/traefik/traefik-dynamic.toml'
      - '{{ containers_data_path }}/traefik/data/acme.json:/acme.json'
    env:
      TZ: '{{ timezone }}'
    labels:
      traefik.enable: 'true'
      traefik.http.routers.traefik.rule:
        'Host(`{{ ansible_fqdn }}`) && PathPrefix(`/traefik`) || Headers(`Referer`, `https://{{ ansible_fqdn }}/traefik/dashboard/`)'
      traefik.http.routers.traefik.entrypoints: 'websecure'
      traefik.http.routers.traefik.service: 'api@internal'
      traefik.http.routers.traefik.middlewares: 'set-security-headers@file, traefik-strip-prefix, traefik-auth'
      traefik.http.middlewares.traefik-strip-prefix.stripprefix.prefixes: '/traefik'
      traefik.http.middlewares.traefik-auth.basicauth.users: >-
        {{ traefik.api.user }}:{{ traefik.api.password | password_hash('bcrypt', ('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
        | shuffle(seed=inventory_hostname) | join)[:21] + ('Oeu' | shuffle(seed=inventory_hostname) | join)[1]) }}
    container_default_behavior: 'no_defaults'
    networks_cli_compatible: yes
    purge_networks: yes
    pull: yes
    state: 'started'
