# "Dummy" ansible-vault file to be used with local development environment.
# It's not encrypted but it's useful to serve as a base for a "real" production vault file.
---
domain_name: 'localhost.localdomain'
traefik:
  api:
    user: 'admin'
    password: 'traefik'
  acme:
    admin_email: 'postmaster@example.com'
nextcloud:
  mariadb:
    root_password: 'mysql'
    user: 'nextcloud'
    password: 'nextcloud'
    database: 'nextcloud'
  redis:
    password: 'redis'
mattermost:
  postgres:
    database: 'mattermost'
    user: 'mattermost'
    password: 'mattermost'
moodle:
  user: 'admin'
  password: 'moodle'
  email: 'admin@example.com'
  mariadb:
    root_password: 'mysql'
    user: 'moodle'
    password: 'moodle'
    database: 'moodle'
dokuwiki:
  username: 'admin'
  full_name: 'Administrator'
  password: 'dokuwiki'
